<?php

namespace saferlanes\controllers;


require_once dirname(__FILE__) . '/../../../../saferlanes/controllers/Saferlanes.php';

/**
 * Test class for Saferlanes.
 * Generated by PHPUnit on 2012-07-25 at 21:31:28.
 */
class SaferlanesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Saferlanes
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Saferlanes;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers saferlanes\controllers\Saferlanes::init
     * @todo Implement testInit().
     */
    public function testInit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers saferlanes\controllers\Saferlanes::start
     * @todo Implement testStart().
     */
    public function testStart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers saferlanes\controllers\Saferlanes::finish
     * @todo Implement testFinish().
     */
    public function testFinish()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}

?>
