<?php

namespace proof\util;


require_once dirname(__FILE__) . '/../../../../proof/util/AbstractObservable.php';

/**
 * Test class for AbstractObservable.
 * Generated by PHPUnit on 2012-07-25 at 13:18:56.
 */
class AbstractObservableTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AbstractObservable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass(__NAMESPACE__.'\\AbstractObservable');

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\util\AbstractObservable::addObservers
     * @todo Implement testAddObservers().
     */
    public function testAddObservers()
    {



        $this->assertSame($this->object, $this->object->attachObserver($this->getMock(__NAMESPACE__.'\\Observer')));


    }

    /**
     * @covers proof\util\AbstractObservable::getObservers
     * @todo Implement testGetObservers().
     */
    public function testGetObserver()
    {
        $stub = $this->getMock(__NAMESPACE__.'\\Observer');

       $this->object->attachObserver($stub);

       $this->assertInstanceOf('proof\util\Observer', $stub);
    }

}

?>
