<?php

namespace proof\util;


require_once dirname(__FILE__) . '/../../../../proof/util/AbstractListing.php';

/**
 * Test class for AbstractListing.
 * Generated by PHPUnit on 2012-07-24 at 21:01:23.
 */
class AbstractListingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AbstractListing
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object =  $this->getMockForAbstractClass(__NAMESPACE__."\\AbstractListing");

        $this->object->expects($this->any())->method($this->anything())->will($this->returnValue($this->object));

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\util\AbstractListing::add
     * @todo Implement testAdd().
     */
    public function testAdd()
    {

        $this->assertSame($this->object, $this->object->add(array(16)));


    }

    /**
     * @covers proof\util\AbstractListing::set
     * @todo Implement testSet().
     * @depends testAdd
     */
    public function testSet()
    {

        $this->object->add('item');

       $this->assertSame($this->object, $this->object->set(0, array(32)));





    }

    /**
     * @covers proof\util\AbstractListing::getIterator
     * @todo Implement testGetIterator().
     */
    public function testGetIterator()
    {

        $this->assertTrue($this->object->getIterator());



    }

}

?>
