<?php

namespace proof\util;


require_once dirname(__FILE__) . '/../../../../proof/util/AbstractEventSource.php';

/**
 * Test class for AbstractEventSource.
 * Generated by PHPUnit on 2012-07-28 at 12:47:50.
 */
class AbstractEventSourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AbstractEventSource
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AbstractEventSource;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\util\AbstractEventSource::getListeners
     * @todo Implement testGetListeners().
     */
    public function testGetListeners()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\util\AbstractEventSource::fire
     * @todo Implement testFire().
     */
    public function testFire()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\util\AbstractEventSource::flushListeners
     * @todo Implement testFlushListeners().
     */
    public function testFlushListeners()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\util\AbstractEventSource::setListeners
     * @todo Implement testSetListeners().
     */
    public function testSetListeners()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}

?>
