<?php

namespace proof\util;


require_once dirname(__FILE__) . '/../../../../proof/util/ArrayList.php';

/**
 * Test class for ArrayList.
 * Generated by PHPUnit on 2012-07-22 at 08:18:19.
 */
class ArrayListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ArrayList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ArrayList(array("one", "one", "one"));

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\util\ArrayList::getIterator
     * @todo Implement testGetIterator().
     */
    public function testGetIterator()
    {

        $iter = $this->object->getIterator();

        $count = 0;

        foreach ($iter as $key=>$value)
        {


            $this->assertEquals($key, $count);
            $this->assertEquals($value, "one");

            $count++;

        }


    }

}
