<?php

namespace proof\util;


require_once dirname(__FILE__) . '/../../../../proof/util/ImportList.php';

/**
 * Test class for ImportList.
 * Generated by PHPUnit on 2012-07-25 at 08:29:43.
 */
class ImportListTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ImportList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ImportList(array("xo1o", 1, "hops"));

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\util\ImportList::import
     * @todo Implement testImport().
     * @expectedException proof\util\BadImportException
     */
    public function testImport()
    {
        $this->object->import();

    }

}

?>
