<?php

namespace saferlanes;


require_once dirname(__FILE__) . '/../../../saferlanes/ControllerStrategy.php';

/**
 * Test class for ControllerStrategy.
 * Generated by PHPUnit on 2012-08-01 at 08:13:23.
 */
class ControllerStrategyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ControllerStrategy
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ControllerStrategy;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers saferlanes\ControllerStrategy::useSearch
     * @todo Implement testUseSearch().
     */
    public function testUseSearch()
    {
        $this->assertInstanceOf('saferlanes\SearchController', $this->object->useSearch()->getController());
    }

       /**
     * @covers saferlanes\ControllerStrategy::useSearchForm
     *
     */
    public function testUseSearchForm()
    {
        $this->assertInstanceOf('saferlanes\SearchFormController', $this->object->useFormSearch()->getController());
    }

    /**
     * @covers saferlanes\ControllerStrategy::useVote
     * @todo Implement testUseVote().
     */
    public function testUseVote()
    {

        $this->assertInstanceOf('saferlanes\VoteController', $this->object->useVote()->getController());

    }

    /**
     * @covers saferlanes\ControllerStrategy::usePost
     * @todo Implement testUsePost().
     */
    public function testUsePost()
    {

        $this->assertInstanceOf('saferlanes\PostController', $this->object->usePost()->getController());

    }

    /**
     * @covers saferlanes\ControllerStrategy::getController
     * @todo Implement testGetController().
     */
    public function testGetController()
    {
       $this->assertNull($this->object->getController());
    }

}

?>
