<?php

namespace saferlanes;


require_once dirname(__FILE__) . '/../../../saferlanes/PlateNumber.php';

/**
 * Test class for PlateNumber.
 * Generated by PHPUnit on 2012-08-04 at 15:19:06.
 */
class PlateNumberTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var PlateNumber
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PlateNumber('pz');

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers saferlanes\PlateNumber::isValid
     * @todo Implement testIsValid().
     */
    public function testIsValid()
    {

        $this->assertFalse($this->object->isValid());

        $this->object = new PlateNumber('pco123');

        $this->assertTrue($this->object->isValid());

    }

    /**
     * @covers saferlanes\PlateNumber::getPlate
     * @todo Implement testGetPlate().
     */
    public function testGetPlate()
    {

        $this->assertEquals('pz', $this->object->getPlate());

    }

}

?>
