<?php

namespace saferlanes\models;


require_once dirname(__FILE__) . '/../../../../saferlanes/models/DriverProvider.php';

/**
 * Test class for DriverProvider.
 * Generated by PHPUnit on 2012-07-26 at 05:24:39.
 */
class DriverProviderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var DriverProvider
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DriverProvider;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers saferlanes\models\DriverProvider::valid
     * @todo Implement testValid().
     */
    public function testValid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}

?>
