<?php

namespace proof\http;


require_once dirname(__FILE__) . '/../../../../proof/http/Header.php';

/**
 * Test class for Header.
 * Generated by PHPUnit on 2012-07-31 at 12:46:14.
 */
class HeaderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Header
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Header('Content-Type: text/html');

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\http\Header::setStatus
     * @todo Implement testSetStatus().
     */
    public function testSetStatus()
    {
        $this->assertInstanceOf(get_class($this->object), $this->object->setStatus(0x500));

    }

    /**
     * @covers proof\http\Header::setText
     * @todo Implement testSetText().
     */
    public function testSetText()
    {
        $this->assertInstanceOf(get_class($this->object), $this->object->setText('/'));

    }

    /**
     * @covers proof\http\Header::send
     * @todo Implement testSend().
     */
    public function testSend()
    {

        $this->assertNull($this->object->send());

        $this->assertNull($this->object->send(TRUE));

    }

}

?>
