<?php

namespace proof\http;


require_once dirname(__FILE__) . '/../../../../proof/http/HttpRequest.php';

/**
 * Test class for HttpRequest.
 * Generated by PHPUnit on 2012-07-25 at 16:42:46.
 */
class HttpRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var HttpRequest
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $_SERVER['REQUEST_URI'] = 'http://trinistorm.org';

        $this->object = new HttpRequest;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\http\HttpRequest::getPaths
     * @todo Implement testGetPaths().
     */
    public function testGetPaths()
    {

        $this->assertInstanceOf('proof\util\ArrayList', $this->object->getPaths());
        
    }

    /**
     * @covers proof\http\HttpRequest::getPost
     * @todo Implement testGetPost().
     */
    public function testGetPost()
    {

        $this->assertInstanceOf('proof\util\Map', $this->object->getPost());

    }

}

?>
