<?php

namespace proof\http;


require_once dirname(__FILE__) . '/../../../../proof/http/InternalServerError.php';

/**
 * Test class for InternalServerError.
 * Generated by PHPUnit on 2012-07-31 at 12:55:19.
 */
class InternalServerErrorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var InternalServerError
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new InternalServerError;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

}

?>
