<?php

namespace proof\app;


require_once dirname(__FILE__) . '/../../../../proof/app/AbstractController.php';

/**
 * Test class for AbstractController.
 * Generated by PHPUnit on 2012-07-25 at 16:17:34.
 */
class AbstractControllerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AbstractController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass(__NAMESPACE__.'\\AbstractController');

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\app\AbstractController::getContent
     * @todo Implement testGetContent().
     */
    public function testGetContent()
    {
        $this->assertInstanceOf('proof\util\Map', $this->object->getContent());
    }

    /**
     * @covers proof\app\AbstractController::next
     * @todo Implement testNext().
     */
    public function testNext()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}

?>
