<?php

namespace proof\app;


require_once dirname(__FILE__) . '/../../../../proof/app/AppLogicController.php';

/**
 * Test class for AppLogicController.
 * Generated by PHPUnit on 2012-07-25 at 17:29:14.
 */
class AppLogicControllerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AppLogicController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass(__NAMESPACE__.'\\AppLogicController');

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\app\AppLogicController::getContent
     * @todo Implement testGetContent().
     */
    public function testGetContent()
    {

        $this->assertNull($this->object->getContent());

    }

    /**
     * @covers proof\app\AppLogicController::next
     * @todo Implement testNext().
     */
    public function testNext()
    {

        $this->assertNull($this->object->next());

    }

}

?>
