<?php

namespace proof\webapp;


require_once dirname(__FILE__) . '/../../../../proof/webapp/BrowserEventDispatcher.php';

/**
 * Test class for BrowserEventDispatcher.
 * Generated by PHPUnit on 2012-07-30 at 05:39:36.
 */
class BrowserEventDispatcherTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var BrowserEventDispatcher
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new BrowserEventDispatcher;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\webapp\BrowserEventDispatcher::bind
     * @todo Implement testBind().
     */
    public function testBind()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\webapp\BrowserEventDispatcher::notifyOnLocationChanged
     * @todo Implement testNotifyOnLocationChanged().
     */
    public function testNotifyOnLocationChanged()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\webapp\BrowserEventDispatcher::notifyOnHttpPost
     * @todo Implement testNotifyOnHttpPost().
     */
    public function testNotifyOnHttpPost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}

?>
