<?php

namespace proof\webapp;


require_once dirname(__FILE__) . '/../../../../proof/webapp/Browser.php';

/**
 * Test class for Browser.
 * Generated by PHPUnit on 2012-07-31 at 13:02:13.
 */
class BrowserTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Browser
     */
    protected $object;
    protected $http;


    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $list =  $this->getMock('proof\util\ArrayList');
        $map = $this->getMock('proof\util\Map');

        $this->http = $this->getMock('proof\http\HttpRequest')->expects($this->any())->method($this->anything())->
                will($this->returnValue(FALSE));
        
        $this->object = new Browser($this->getMock('proof\webapp\Page', NULL, array($list, $map)),
                $this->getMock('proof\webapp\BrowserSubscriber'));


    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }


    /**
     * @covers proof\webapp\Browser::submitGet
     *
     */
    public function testSubmitGet()
    {
        $this->assertNull($this->object->submitGet($this->http));

    }

    /**
     * @covers proof\webapp\Browser::submitPath
     *
     */
    public function testSubmitPath()
    {

        $this->assertNull($this->object->submitPath($this->http));

    }

    /**
     * @covers proof\webapp\Browser::submitPost
     */
    public function testSubmitPost()
    {

        $this->assertNull($this->object->submitPost($this->http));

    }

    /**
     * @covers proof\webapp\Browser::submit
     * @todo Implement testSubmit().
     */
    public function testSubmit()
    {

        $this->assertNull($this->object->submit($this->http));

    }

    /**
     * @covers proof\webapp\Browser::changePage
     * @todo Implement testChangePage().
     */
    public function testChangePage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

    /**
     * @covers proof\webapp\Browser::getPage
     * @todo Implement testGetPage().
     */
    public function testGetPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );


        }


}

?>
