<?php

namespace proof\webapp;


require_once dirname(__FILE__) . '/../../../../proof/webapp/BrowserRequestEvent.php';

/**
 * Test class for BrowserRequestEvent.
 * Generated by PHPUnit on 2012-07-31 at 20:10:44.
 */
class BrowserRequestEventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var BrowserRequestEvent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass
                (__NAMESPACE__."\\BrowserRequestEvent", array(new \stdClass(), $this->getMock('proof\util\Aggregate')));

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\webapp\BrowserRequestEvent::__constuct
     * @todo Implement test__constuct().
     */
    public function test__constuct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}

?>
