<?php

namespace proof\webapp;


require_once dirname(__FILE__) . '/../../../../proof/webapp/Fork.php';

/**
 * Test class for Fork.
 * Generated by PHPUnit on 2012-07-28 at 11:50:09.
 */
class ForkTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Fork
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        $controller = $this->getMock(__NAMESPACE__."\\Controller");

        $aggregate = $this->getMockForAbstractClass("proof\util\AbstractAggregate");

        $this->object = new Fork (new \stdClass, $controller, $aggregate);

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\webapp\Fork::getChild
     * @todo Implement testGetChild().
     */
    public function testGetChild()
    {

        $this->assertTrue($this->object->getChild() instanceof  Controller);

    }

    /**
     * @covers proof\webapp\Fork::getArgs
     * @todo Implement testGetArgs().
     */
    public function testGetArgs()
    {
        
        $abs =  "proof\util\AbstractAggregate";

        $this->assertTrue($this->object->getArgs() instanceof $abs);

    }

}

?>
