<?php

namespace proof\webapp;


require_once dirname(__FILE__) . '/../../../../proof/webapp/HttpPostEvent.php';

/**
 * Test class for HttpPostEvent.
 * Generated by PHPUnit on 2012-07-30 at 05:32:11.
 */
class HttpPostEventTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var HttpPostEvent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new HttpPostEvent($this->getMock('proof\webapp\Browser'),
                $this->getMock('proof\util\Map'));

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\webapp\HttpPostEvent::getPost
     * @todo Implement testGetPost().
     */
    public function testGetPost()
    {

        $this->assertInstanceOf('proof\util\Map', $this->object->getPost());
    }

}

?>
