<?php

namespace proof\webapp;


require_once dirname(__FILE__) . '/../../../../proof/webapp/Scheduler.php';

/**
 * Test class for Scheduler.
 * Generated by PHPUnit on 2012-07-28 at 12:17:17.
 */
class SchedulerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Scheduler
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Scheduler;

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\webapp\Scheduler::execute
     * @expectedException \BadMethodCallException
     *
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

        $controller = $this->getMock(__NAMESPACE__ . "\\Controller")->expects($this->any())->method('main')->
                will(throwException(new \BadMethodCallException()));

        $this->object->put($controller);

    }

    /**
     * @covers proof\webapp\Scheduler::put
     * @todo Implement testPut().
     */
    public function testPut()
    {

        $controller = $this->getMock(__NAMESPACE__ . "\\Controller");

        $aggregate = $this->getMockForAbstractClass("proof\util\AbstractAggregate");

        $this->assertInstanceOf(get_class($this->object), $this->object->put($controller, $aggregate));

    }

    /**
     * @covers proof\webapp\Scheduler::notify
     * @todo Implement testNotify().
     */
    public function testNotify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );

    }

}

?>
