<?php

namespace proof\webapp;


require_once dirname(__FILE__) . '/../../../../proof/webapp/WebPage.php';

/**
 * Test class for WebPage.
 * Generated by PHPUnit on 2012-07-30 at 12:19:07.
 */
class WebPageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var WebPage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

        $this->object = $this->getMockForAbstractClass(__NAMESPACE__."\\WebPage");

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers proof\webapp\WebPage::addProperty
     * @todo Implement testAddProperty().
     */
    public function testAddProperty()
    {

        $this->assertInstanceOf(get_class($this->object),$this->object->addProperty("title", "bar"));

    }

    /**
     * @covers proof\webapp\WebPage::addTemplate
     * @todo Implement testAddTemplate().
     */
    public function testAddTemplate()
    {

        $this->assertInstanceOf(get_class($this->object),$this->object->addTemplate("/srv/foo/bar"));

    }

    /**
     * @covers proof\webapp\WebPage::getProperties
     * @todo Implement testGetProperties().
     */
    public function testGetProperties()
    {

        $this->object->addProperty("name", "sana");

        $props = $this->object->getProperties();

        foreach ($props as $value)
        {
            $this->assertEquals("sna", $value);
        }

    }

    /**
     * @covers proof\webapp\WebPage::getTemplates
     * @todo Implement testGetTemplates().
     */
    public function testGetTemplates()
    {

        $this->object->addTemplate("/srv/foo/bar/");

        $temps = $this->object->getTemplates();

        foreach ($temps as $value)
        {
            $this->assertEquals("/srv/foo/bar/", $value);
        }

    }

}